### ISSUE TITLE
Make checkboxes on retro page able to be checked

### ISSUE THREAD

**Issue by loganmeetsworld** [loganmeetsworld/RetroRails#6]
You have to go to the individual note page in order to edit the "complete" status of the retro note. I would like to change this to a clickable button to toggle the the "complete" status on and off.

**Comment by dezshino** [comment]
I'd like to work on this!

**Comment by loganmeetsworld** [comment]
@desireepoland I added you as a colab! This would be great. Right now the boxes are just images but it would be great if instead of going to the edit page you could click on them and just make them either done or undone. Thanks!

**Comment by dezshino** [comment]
@loganmeetsworld I just pull requested, let me know if anything's unclear :)
